//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castle.DynamicLinqQueryBuilder.Samples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C040dsnContrat
    {
        public string id { get; set; }
        public string periodeDsn { get; set; }
        public string ownerId { get; set; }
        public string C005declarationid { get; set; }
        public string C030dsnSalarieid { get; set; }
        public Nullable<System.DateTime> C40001ContratDateDebut { get; set; }
        public string C40002ContratStatutConventionnel { get; set; }
        public string C40003ContratStatutRC { get; set; }
        public string C40004ContratPcsEse { get; set; }
        public string C40005ContratComplementPcsEse { get; set; }
        public string C40006ContratLibelleEmploi { get; set; }
        public string C40007ContratNature { get; set; }
        public string C40008ContratDispositifPolitique { get; set; }
        public string C40009ContratNumero { get; set; }
        public Nullable<System.DateTime> C40010ContratDateFinPrevisionnelle { get; set; }
        public string C40011ContratUniteMesure { get; set; }
        public Nullable<decimal> C40012ContratQuotiteCategorie { get; set; }
        public Nullable<decimal> C40013ContratQuotite { get; set; }
        public string C40014ContratModaliteTemps { get; set; }
        public string C40016ContratComplementBase { get; set; }
        public string C40017ContratCcn { get; set; }
        public string C40018ContratRegimeMaladie { get; set; }
        public string C40019ContratLieutravail { get; set; }
        public string C40020ContratRegimeVieillesse { get; set; }
        public string C40021ContratMotifRecours { get; set; }
        public string C40022ContratCodeCaisseCongesPayes { get; set; }
        public Nullable<decimal> C40023ContratTauxFraisProfessionnels { get; set; }
        public string C40024ContratTravailleurEtranger { get; set; }
        public string C40025ContratMotifExclusionDSN { get; set; }
        public string C40026ContratStatusEmploi { get; set; }
        public string C40027ContratCodeAffectationAC { get; set; }
        public string C40028ContratNumeroInterne { get; set; }
        public string C40029ContratTypeGestionAC { get; set; }
        public Nullable<System.DateTime> C40030ContratDateAdhesion { get; set; }
        public Nullable<System.DateTime> C40031ContratDateDenonciation { get; set; }
        public Nullable<System.DateTime> C40032ContratDateConventionGestion { get; set; }
        public string C40033ContratNumeroConventionGestion { get; set; }
        public string C40035ContratCodeGestionnaireRisque { get; set; }
        public string C40036ContratCodeEmploisMultiples { get; set; }
        public string C40037ContratCodeEmployeursMultiples { get; set; }
        public string C40038ContratCodeMetier { get; set; }
        public string C40039ContratCodeRegimeRisqueAccidentTravail { get; set; }
        public string C40040ContratCodeRisqueAccidentTravail { get; set; }
        public string C40041ContratPositionnementConventionCollective { get; set; }
        public string C40042ContratCodeStatutCategorielAPECITA { get; set; }
        public Nullable<decimal> C40043ContratTauxAccidentTravail { get; set; }
        public string C40044ContratSalarieTempsPartielCotisantTempsPlein { get; set; }
        public string C40045ContratRemunerationPourboire { get; set; }
        public string C40046ContratSiretEtablissementUtilisateur { get; set; }
        public string C40047ContratNumeroCertificationSociale { get; set; }
        public string C40048ContratNumeroLabel { get; set; }
        public string C40049ContratNumeroLicenceEntrepreneurSpectacle { get; set; }
        public string C40050ContratNumeroObjetSpectacle { get; set; }
        public string C40051ContratStatutOrganisateurSpectacle { get; set; }
    }
}
