//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castle.DynamicLinqQueryBuilder.Samples.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordId
    {
        public long Id { get; set; }
        public int Block { get; set; }
        public string Uuid { get; set; }
        public long FileId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedOwner { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedOwner { get; set; }
        public bool IsDeleted { get; set; }
    }
}
